### ISSUE TITLE
Erroneous type hints for `SimAIClient`

### ISSUE THREAD

**Issue by bastbu** [ansys/pysimai#103]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

When instantiating a `SimAIClient`, the type checker (Pyright) displays the initializer's parameter types incorrectly. This can be reproduced by running Pyright from the command line, as well as the type hints that VS Code displays on hovering over the instance declaration.

### 📝 Steps to reproduce

Instantiate a SimAI client as follows:

```py
from ansys.simai.core.client import SimAIClient


_ = SimAIClient(
    organization="foo",
    credentials={
        "username": "bar",
        "password": "baz",
    },
)
```

Run Pyright in strict mode and observe the following errors:

```
/workspaces/test.py
  /workspaces/test.py:5:18 - error: Argument of type "Literal['foo']" cannot be assigned to parameter "organization" of type "Credentials | None"
    Type "Literal['foo']" is not assignable to type "Credentials | None"
      "Literal['foo']" is not assignable to "Credentials"
      "Literal['foo']" is not assignable to "None" (reportArgumentType)
  /workspaces/test.py:6:17 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "credentials" of type "str | None"
    Type "dict[str, str]" is not assignable to type "str | None"
      "dict[str, str]" is not assignable to "str"
      "dict[str, str]" is not assignable to "None" (reportArgumentType)
```

When hovering over the `SimAIClient` type, VS Code is also displaying erroneous type hints:

![Image](https://github.com/user-attachments/assets/11a7c874-459e-4024-adb5-0bc05ced9460)

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

No ANSYS version needed, the error occurs within the SDK

### 🐍 Which Python version are you using?

3.12

### 📦 Installed packages

ansys-simai-core==0.2.4

**Comment by tmpbeing** [comment]
Hello. Thank you for opening an issue on this. 
Interesting bug, we use the `pydantic` library to define those types and looking at [the code](https://github.com/ansys/pysimai/blob/main/src/ansys/simai/core/utils/configuration.py#L81), the types are correct but it seems the types computed by pyright are off by one : the type of first argument (`interactive`) is the type of the second field of the `ClientConfig` (`url`) and so on.
Pinging @awoimbee as he knows more than me about types and pydantic.

**Comment by awoimbee** [comment]
Hi, thanks for the issue !
The problem is `steal_kwargs_type` that applies `ClientConfig`'s types to `SimAIClient`, I think the type of `interactive` is being applied to `self` 😬.
